version: '3.8'

services:
  orders:
    build: .
    command: "gunicorn -c gunicorn.py orders.wsgi"
    volumes:
      - ./orders/:/user/src/orders
    ports: 
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}

  nginx:
    restart: always
    image: nginx
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./nginx:/user/src/orders/nginx/conf.d
    depends_on:
      - orders

volumes:
  postgres_data:
