version: '3.9'

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/orders
    ports: 
      - 8000:8000
    depends_on:
      - db
    network_mode: host

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    container_name: pgdb
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      PGDATA: ${PG_DATA}
