# Generated by Django 4.2.6 on 2023-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_order_options_shop_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='floor',
            field=models.CharField(blank=True, max_length=15, verbose_name='Этаж'),
        ),
    ]
