# Generated by Django 4.2.6 on 2023-10-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
